### ISSUE TITLE
RemoteService shouldn't not run all the time

### ISSUE THREAD

**Issue by tdkl** [kelsos/mbrc#68]
As far I've seen, RemoteService is run at boot and keeps running indefinitely despite I didn't even run the app. 

Now imagine if all apps would do that ? Please keep the responsibility regarding device resources and close the services/don't run them before the app even opens.

**Comment by kelsos** [comment]
I am pretty sure that the issue has a different cause. 

To start a service on boot you have to listen for a specific broadcast intent, for which I never listen. 
In fact at some point I was testing this exact thing and I am 100% the service didn't start on boot. I even tested the exit button that closes the service completely. 

This doesn't mean however that bug doesn't exist. I think it just might have a different cause, that I completely missed before.

I also have a broadcast receiver for incoming calls that is used to decrease the volume of the application, and there is a high probability that the service starts on an incoming call.

Thanks for mentioning the issue, because I might have found the real reason for the issue. 

You are not wrong about resource management, but keep in might how easy it is some times to miss something that might have unintended consequences.

**Comment by kelsos** [comment]
After some investigation it was not related to the incoming call broadcast receiver. It seems that the application process itself gets started on boot. 

For some reason the application's onCreate is called by the OS on boot. I have no clue why would this happen, it doesn't seem widget related.

As soon as I find a way that doesn't break the whole application functionality I will fix it.

**Comment by tdkl** [comment]
Awesome, thanks for taking the time for this.

**Comment by kelsos** [comment]
This has been fixed and should be part of v1.0.0
